---
functional:
  - Должна быть возможность создавать игры со случайными игроками.
  - Должна быть возможность создавать игры с друзьями.
  - Должна быть возможность создавать игры с ботами.
  - Должна быть возможность просмотра рейтингов.
  - В игре должна быть возможность выбора языка программирования.
  - Должна быть возможность просмотра игр других людей.
  - У зрителей должен быть чат.
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть удобным на мобильном устройстве.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей).
implicit:
  - Должна быть возможность зарегистрироваться на сайте.
  - Должна быть возможность зарегистрироваться на сайте с помощью GitHub.
  - Должна быть возможность зарегистрироваться на сайте с помощью Discord.
  - Должна быть возможность авторизироваться под своим аккаунтом на сайте.
  - Должна быть возможность авторизироваться под своим аккаунтом GitHub на сайте.
  - Должна быть возможность авторизироваться под своим аккаунтом Discord на сайте.
  - Должна быть возможность выбирать сложность заданий.
  - Должна быть возможность попробовать игру без регистрации.
  - Должна быть возможность просматривать открытые лобби, турниры и законченные игры.
  - Должна быть возможность просматривать таблицу лидеров.
  - Должна быть возможность просматривать свою статистику.
  - Должна быть возможность просматривать рейтинг игроков.
  - Должна быть возможность просматривать и создавать задания для игр.
  - Должна быть возможность создавать турниры.
